# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16]
        os: [ubuntu-latest]
    # The type of runner that the job will run on
    
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      
      - name: Initialize Project
        run: yarn init -y

      # Runs a single command using the runners shell
      - name: Test File
        run: |
          mkdir -pv build/stage/v0.0.1/
          touch build/stage/v0.0.1/license
          
      - name: Echo Accent Token
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
          echo ${{ secrets.ACCENT_TOKEN }}

      # 读取当前版本号
      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          # 读取dist/package.json的，而不是根路径下的package.json
          path: ./package.json
          property: version

      - name: 建立GitHub Release & 上传附件
        uses: meeDamian/github-release@2.0
        env:
          # 配置github token （这个无需去github配置，默认存在的）
          token: ${{ secrets.ACCESS_TOKEN }}
          # 标签名
          tag: v${{steps.version.outputs.value}}
          # release名
          name: v${{steps.version.outputs.value}}
          # 是否为草稿
          draft: false
          # 是否为预发布
          prerelease: false
          # 文件路径
          files: build/stage/*/*

