# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      # 配置github token （这个无需去github配置，默认存在的）
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    outputs:
      version: 0.0.1

    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v3

      - name: 建立GitHub Release
        id: create_release
        uses: actions/create-release@latest
        with:
          # 标签名
          tag_name: v0.0.1
          # release名
          release_name: v0.0.1
          # 是否为草稿
          draft: false
          # 是否为预发布
          prerelease: true

  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
    # The type of runner that the job will run on
    
    needs: release
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Generate Assets
        run: |
          mkdir build
          mkdir build/stage
          mkdir build/stage/v0.0.1
          echo 'this is tset' > build/stage/v0.0.1/license
          
      - name: Show Directory | Files
        run: |
          ls build/stage/v${{ needs.release.outputs.version }}/

      # 上传Release Asset
      - name: 上传Release Asset
        id: upload-release-asset
        uses: alexellis/upload-assets@0.2.2
        env:
          # 配置github token （这个无需去github配置，默认存在的）
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 上传URL为建立GitHub Release步骤的输出值，可经过配置的id获取
          # upload_url: ${{ steps.create_release.outputs.upload_url }}
          # 上传文件信息
          asset_paths: '["build/stage/*/*"]'
